spring:
  application:
    name: snowflake
  server:
    port: 8080

#zookeeper配置
zookeeper:
  server: 192.168.20.66:2181
  sessionTimeoutMs: 6000
  connectionTimeoutMs: 6000
  maxRetries: 3
  baseSleepTimeMs: 1000


