server:
  port: 8885


dubbo:
  #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者
  application:
    name: Provider
  #注册中心配置，用于配置连接注册中心相关信息
  registry:
    address: zookeeper://127.0.0.1:2181
  #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受
  protocol:
    name: dubbo
    port: 20880

  scan: com.gold.common.impl